#!/bin/sh
# Give a battery name (e.g. BAT0) as an argument.

case $BLOCK_BUTTON in
    3) notify-send "<b>🔋 Battery module:</b>
🔋: discharging
🛑: off-line
♻: stagnant charge
🔌: on-line
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

capacity=$(acpi -b | grep -E -o '[0-9][0-9]?%' | sed -e 's/.\{1\}$//')
status=$(acpi -a | awk '{ print $3 }')

if [ "$capacity" -ge 75 ]; then
	color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
else
	color="#ff0000"
	warn="❗"
fi

[ -z $warn ] && warn=""
[ "$status" = "on-line" ] && color="#ffffff"


echo  "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/off-line/🛑/;s/on-line/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
echo  "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/off-line/🛑/;s/on-line/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
echo "$color"
