#!/bin/bash

packages=$(dnf updateinfo --list --enhancement --newpackage --bugfix --sec-severity Critical --sec-severity Important | tail -n +2)
numPackages=$(echo -e "$packages" | wc -l)

echo "$numPackages"
echo "$numPackages"

if [ $numPackages -eq 0 ]
then
    echo "#00ff00"
else
    echo "#ff0000"
fi

case $BLOCK_BUTTON in
      # right click: show packages
      3) notify-send "Packages" "$packages" ;;
esac

exit 0
